### ISSUE TITLE
Doubt with FastDL

### ISSUE THREAD

**Issue by paulocrash** [OpenGamePanel/Module-Fast_Download#15]
Currently in my OGP Panel FastDL is configured as follows ...

If I add new files to the server, example CSGO, and click Update / Synchronize FastDL it deletes all files and synchronizes again.

It would be possible to do that whenever I add a new file it only synchronizes this new file, without changing or deleting the ones that already have.

**Comment by rocco27** [comment]
Whaaaat? Don't think you use same OGP as we... :)

**Comment by Zorrototo** [comment]
Also we don't accept support on GitHub, use the forum instead, thanks.
